DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS push_tokens;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS otp_challenges;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS user_role;
