package storage

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// validKeyPattern matches the only shape a key generated by
// RandomObjectKey ever has: one or more path segments of lowercase
// hex/ASCII, dots, dashes, underscores. Enforcing this allowlist before
// any path arithmetic means safety is a property of the key's format, not
// solely of filepath.Clean's traversal-collapsing behavior — a key that
// doesn't match this shape is rejected outright, including any key
// containing "..", backslashes, drive letters, or non-ASCII bytes that
// could behave surprisingly across filesystems.
var validKeyPattern = regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9._-]*(/[a-zA-Z0-9][a-zA-Z0-9._-]*)*$`)

// LocalStorage writes files under a configured media directory, served via
// an authenticated static route (blueprint §4.4). Object keys become
// relative file paths; keys are validated to prevent path traversal
// escaping the media root.
type LocalStorage struct {
	baseDir string
	// urlPrefix is the route path (mounted in main.go) that serves files
	// from baseDir, e.g. "/media".
	urlPrefix string
	// publicBaseURL, when set, is prepended to make an absolute URL (e.g.
	// "https://api.example.com") so clients on other origins can load media.
	// Empty → URLs stay relative (dev default).
	publicBaseURL string
}

func NewLocalStorage(baseDir, urlPrefix, publicBaseURL string) (*LocalStorage, error) {
	absBase, err := filepath.Abs(baseDir)
	if err != nil {
		return nil, fmt.Errorf("storage: resolve media dir: %w", err)
	}
	if err := os.MkdirAll(absBase, 0o755); err != nil {
		return nil, fmt.Errorf("storage: create media dir: %w", err)
	}
	return &LocalStorage{
		baseDir:       absBase,
		urlPrefix:     strings.TrimSuffix(urlPrefix, "/"),
		publicBaseURL: strings.TrimSuffix(publicBaseURL, "/"),
	}, nil
}

func (s *LocalStorage) resolvePath(key string) (string, error) {
	// Reject anything not shaped like a key RandomObjectKey would produce
	// before doing any path arithmetic at all — this is the primary
	// defense, not filepath.Clean's traversal-collapsing.
	if !validKeyPattern.MatchString(key) {
		return "", fmt.Errorf("storage: key %q has an invalid format", key)
	}

	cleanKey := filepath.Clean("/" + key) // normalize, collapsing any ".."
	fullPath := filepath.Join(s.baseDir, cleanKey)
	// Defense in depth: confirm the resolved path is still under baseDir
	// before ever touching the filesystem, in case the allowlist above is
	// ever loosened in the future.
	if !strings.HasPrefix(fullPath, s.baseDir+string(os.PathSeparator)) && fullPath != s.baseDir {
		return "", fmt.Errorf("storage: key %q resolves outside media root", key)
	}
	return fullPath, nil
}

func (s *LocalStorage) Put(ctx context.Context, key string, r io.Reader, contentType string) error {
	fullPath, err := s.resolvePath(key)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		return fmt.Errorf("storage: create parent dir: %w", err)
	}

	f, err := os.OpenFile(fullPath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
	if err != nil {
		return fmt.Errorf("storage: open file for write: %w", err)
	}
	defer f.Close()

	if _, err := io.Copy(f, r); err != nil {
		return fmt.Errorf("storage: write file: %w", err)
	}
	return nil
}

// URL returns the public route path that serves this key, made absolute with
// publicBaseURL when configured so clients on other origins can load it. ttl
// is unused for local storage — the /media route is public (object keys are
// unguessable), so there is no expiry mechanism.
func (s *LocalStorage) URL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	cleanKey := filepath.ToSlash(filepath.Clean("/" + key))
	return s.publicBaseURL + s.urlPrefix + cleanKey, nil
}

func (s *LocalStorage) Delete(ctx context.Context, key string) error {
	fullPath, err := s.resolvePath(key)
	if err != nil {
		return err
	}
	if err := os.Remove(fullPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("storage: delete file: %w", err)
	}
	return nil
}

// ResolveServePath is used by the authenticated serve handler to map an
// incoming request path back to a filesystem path, with the same
// traversal guard as Put/Delete.
func (s *LocalStorage) ResolveServePath(key string) (string, error) {
	return s.resolvePath(key)
}
